#!/usr/bin/bash

cd "$(dirname $0)"
root="$(pwd)/jsl_support"
cd - >/dev/null 2>&1

#
# Because of some problem with the build process, pyspidermonkey doesn't even
# know to link against libjs.so, let alone know where to find it.
#
export LD_PRELOAD="$root/libjs.so"

#
# javascriptlint defines its own 'warnings' module, and without explicitly
# putting the system libraries first in PYTHONPATH, standard modules that
# 'import warnings' end up pulling from that one instead of the python-shipped
# ones.  That's obviously a bug or a misconfiguration somewhere else, but I
# have only so much sanity left to spend today.
#
export PYTHONPATH="$PYTHONPATH:/opt/local/lib/python2.6"

export PYTHONPATH="$PYTHONPATH:$root/javascriptlint"

#
# We have to explicitly use a path to a python 2.6.
#
exec python2.6 "$root/jsl.py" $@
